### PR TITLE
Redirect user to /term/new when adding new term

### LINKED ISSUE #301: Update save button functionality on new term page
Currently, clicking "Save" button on the "New Term" page redirects users to the terms page, disrupting the workflow. Instead, let's reset the form and stay on the same page after saving.

### PR DESCRIPTION
**Pull request by Jayanth-Parthsarathy**
Fixes #301.
- [x] Allows the user to stay on the same page if adding new term.
- [x] Preserves existing functionality for editing terms.

### CODE REVIEW

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jzohrab. Please have a look at this and let me know if there are changes to be made.

**Comment by jzohrab** [comment]
Looks good, thank you @Jayanth-Parthsarathy .  This section of the code is a bit weird, I'll merge your change and then might tweak a bit more.

**Comment by jzohrab** [comment]
Simplified a bit more in `develop` based on your work.  Thank you!

**Comment by jzohrab** [comment]
Launched in 3.2.5.

**Pull request merged**
