### PR TITLE
Fix Arabic Google Translate URL

### PR DESCRIPTION
**Pull request by imamcr**
Changed the URL from Spanish to English.

### CODE REVIEW

**Comment by M-Biggles** [comment]
Wow! We actually missed this one in our spreadsheet! Just changed it there too! Thanks :)

**Comment by jzohrab** [comment]
:-) thx.

**Comment by jzohrab** [comment]
ah conflicts due to how Lute handles this data, which is really no good.  There's an issue to change this baselining stuff, it's too messy.

I'll just make the change in develop as well, based on your note, and re-baseline.

**Comment by jzohrab** [comment]
Manually pulled into develop in commit `66c3466`, thx @imamcr .  Closing this, no longer needed.  Cheers!

**Comment by jzohrab** [comment]
Launched in 3.2.4.

**Pull request closed without merging**
