### PR TITLE
Add words per page in the book creation page

### PR DESCRIPTION
**Pull request by fanyingfx**

### CODE REVIEW

**Comment by jzohrab** [comment]
Thanks @fanyingfx 👍 

I'm looking at the branch now.  Some of the code should be moved into the domain model so I'm making adjustments in my own branch (off of yours).  When it's done I'll PR back into your branch.

I've also re-arranged the form fields: the max word count belongs next to the text fields.

I've also decrease the min word count to 10.  That number might seem very low, but for complete beginners in a language, seeing something sentence-by-sentence might be useful.  The default is still 250, and max is what you set it as.

**Comment by jzohrab** [comment]
@fanyingfx , I PR'd back into your branch :-) but we can also just merge my branch into `develop`, as it has your commits and mine.  Take a peek at the PR (https://github.com/fanyingfx/lute-v3/pull/1) -- cheers!

**Comment by fanyingfx** [comment]
Thanks jz,  your adjustments make code better consistency and  more user-friendly. And I think using your branch is better for the project management. I think I can close this pr.

**Comment by jzohrab** [comment]
Hi @fanyingfx , I've opened a PR from my branch to develop: https://github.com/jzohrab/lute-v3/pull/157.  We can chat there if needed.  Take a look, LMK if any questions etc.  Thx for getting this started!

**Pull request closed without merging**
