### PR TITLE
Add PDF import support for books (Issue #93)

### PR DESCRIPTION
**Pull request by dgc08**
Implement issue #93 

I took the PR for the epub support as template and chnaged it accordingly.

 I used `PyPDF2` as library, the license should be fine: [ https://pypi.org/project/PyPDF2/](https://pypi.org/project/PyPDF2/)

### CODE REVIEW

**Comment by jzohrab** [comment]
Hi @dgc08 -- this failed one of the acceptance tests, can you take a look?

**Review by jzohrab — CHANGES_REQUESTED** [review]
Failed acceptance test.

**Comment by dgc08** [comment]
The acceptance test should work now. The sample PDF file contained an extra page number, which also got imported. Didn't run the test beforehand, sorry.

**Comment by jzohrab** [comment]
No problem that’s what the tests are there for. Thanks for adding the test
it’s a big help for stability.

**Comment by dgc08** [comment]
kinda screwed up my fork, wait a moment before merging

**Comment by dgc08** [comment]
ok its fine now

**Comment by dgc08** [comment]
I hope that's it. Thank you for your patience with me, Lute is the first Open Source project / larger project in general that i contribute to, pytest and that stuff is still new to me

**Comment by jzohrab** [comment]
It’s a super contribution so thank you. I’ll try it out soon with a bigger
pdf to see how it works, and will review the code again.

For a first PR it’s great!  👍

**Comment by jzohrab** [comment]
Hi @dgc08 -- I did an import of a large file and found a few places where the import adds some spaces, eg

> image

vs the original pdf:

> image

This happens fairly frequently.  It's almost certain that it's due to the PDF parser library ... should check.

**Comment by jzohrab** [comment]
Yes, it's the library, there's a good write up by the author(s) in these links:

* https://stackoverflow.com/questions/76546531/why-does-pypdf-stuff-text-with-extra-spaces-when-extracting-text
* https://github.com/py-pdf/pypdf/issues/1507

Per the authors:

> Getting whitespaces right is notoriously hard. @pubpub-zz is the expert in that topic; I'll leave it to him to decide if we should leave this issue open. The issue is that PDF does not (necessarily) represent the words as words internally. In the worst case, it just gives the absolute position of each character in the document.

So, I think this should be fine as it is, but we should mention somewhere that PDF imports are extremely tricky.

**Comment by jzohrab** [comment]
Added a flash:

> image

**Pull request merged**
