### PR TITLE
#267 remove backup/settings.html

### PR DESCRIPTION
**Pull request by EikeMenzel**
I've reviewed the usage of lute/templates/backup/settings.html and confirmed it's not utilized anywhere in our project. Following the action items outlined in Issue #267, I've removed this file to maintain code cleanliness and efficiency.

Regarding [lute/templates/settings/form.html](https://github.com/jzohrab/lute-v3/blob/master/lute/templates/settings/form.html), do we consider this file critical enough to warrant a backup? I think our old settings.html was replaced by it.

Please share your thoughts or approval on this matter so we can proceed accordingly.

### CODE REVIEW

**Comment by jzohrab** [comment]
Hello @EikeMenzel - thank you for looking into this :-)  .

Re "do we consider this file critical enough to warrant a backup? " - can you clarify?  It's committed to git, so it's never really "lost".  Cheers!

**Review by jzohrab — APPROVED** [review]
LGTM, I searched as well.  Just awaiting response re "backup the file."  Thank you!

**Comment by EikeMenzel** [comment]
All good, I think I just got generally confused, why this folder exists at all. I agree with you, keeping a copy shouldn't be necessary.  

From my side, you can merge it. o7

**Comment by jzohrab** [comment]
Thank you very much!

**Pull request merged**
