### PR TITLE
Term form: table -> flex/grid

### PR DESCRIPTION
**Pull request by webofpies**
replaced `table` layout for the term form to `flex`/`grid`
added other adjustments to make the form more comfortable to work with

changes:
- new styles added to `styles.css` and `styles-compact.css` deleted

### CODE REVIEW

**Comment by webofpies** [comment]
need to fix the "romanization" field quickly..

**Comment by jzohrab** [comment]
Discussions about font sizes and vert space happening in discord.

**Comment by webofpies** [comment]
decreased button font-size and overall height of the form

**Comment by jzohrab** [comment]
Thanks, looks great!

**Pull request merged**
